version: '3.8'
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - URL_DATABASE = "mongodb+srv://lmsandoval367:GHAQVR21ZJzal4s5@lauras.5g8njzx.mongodb.net/?retryWrites=true&w=majority&appName=LauraS"



  frontend:
    build:
      context: ./Frontend
      dockerfile:  dockerfile
    ports:
      - "5176:5173"
    depends_on:
      - backend
    networks:
      - app-network
    

networks:
  app-network:
    driver: bridge
